# Generated by Django 4.2.5 on 2023-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cpf', models.IntegerField(max_length=11)),
                ('telefone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
