# Generated by Django 4.2.5 on 2023-09-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
