# Generated by Django 4.2.5 on 2023-09-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0002_alter_usuarios_cpf_alter_usuarios_telefone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
